### ISSUE TITLE
Demo Sample: Gesture/Swipe Detection

### ISSUE THREAD

**Issue by PlastiBots** [Xinyuan-LilyGO/LilyGo-T-RGB#12]
Paying it forward.  Attached is a demo for detection of screen swipes (L,R,U,D). It's crude, but it works for my needs. Feel free to use and modify as needed, but pls retain the credit and license info at the top.  Compiled in Arduino IDE 2.0 with ESP32 v2.0.4 and T-RGB libraries as of the date of this posting.  Note, most of the files within are provided as part of existing T-RGB examples.  Only addition is the font.  LilyGo, feel free to add this to the examples section as I don't have time for pull requests etc. ;-) 

[TouchGesturesTestingV2.zip](https://github.com/Xinyuan-LilyGO/T-RGB/files/10262664/TouchGesturesTestingV2.zip)

**Comment by mmMicky** [comment]
I will upload this routine to the repository. thank you for your support.
