### ISSUE TITLE
Converting image to array - image does not display correctly

### ISSUE THREAD

**Issue by extremerotary** [Xinyuan-LilyGO/LilyGo-T-RGB#36]
Good morning,
I am a bit of a newbie to LCD displays. I installed this library in my IDE and successfully uploaded the display example showing the company logo. As a next step, I want to display my own image. I have a 480x480px image. I saved it as a bmp and then went to this site - https://tomeko.net/online_tools/file_to_hex.php?lang=en to convert it to hex. I then edited the example, included my new file with a const unsigned char array[] equal to the hex array I received from the converter tool. I then updated the line to display the image - esp_lcd_panel_draw_bitmap(panel_handle, 0, 0, 480, 480, rotor); However, when I compile and upload the sketch, it does not display correctly. I'm confident it's an error on my end, but I'm not clear on the steps specific to this LCD to generate a hex array that can be displayed properly. Just looking for a little guidance. Thanks for you time.

**Comment by lewisxhe** [comment]
I recorded a simple [video](https://youtu.be/55RWcsippmA) to demonstrate my commonly used image conversion tools. I hope it will be helpful to you.
