### ISSUE TITLE
I2C with Arduino Mega

### ISSUE THREAD

**Issue by Noor-H** [Xinyuan-LilyGO/LilyGo-T-RGB#38]
Hi, I am trying to connect the LilyGO (round 2.1 inch) to an Arduino Mega on I2C using the groove but cannot do so. I2c scan function detects the address of arduino but when i try to transmit something using Wire.write() it does not work. Can anyone please help.

**Comment by lewisxhe** [comment]
Groove's I2C SDA and SCL share the bus with the screen's SDA and SCL. If the screen touch function is normal, then the I2C description is normal.
