### ISSUE TITLE
Touch not working properly 

### ISSUE THREAD

**Issue by harishi** [Xinyuan-LilyGO/LilyGo-T-RGB#40]
Hi I am having a T-RGB  ESP32-S3 Round screen. when the firmware is flashed TRGB_CST820_2_1_Inc.bin some time screen is working, but not all the time.
when the display is not turned on during that time, I was getting I2c read error 

Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x420c893e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
E (38) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
E (38) vfs_fat_sdmmc: sdmmc_card_init failed (0x107).
[   480][E][SD_MMC.cpp:138] begin(): Failed to initialize the card (0x107). Make sure SD card lines have pull-up resistors in place.
[  7833][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[  7838][E][Wire.cpp:513] requestFrom(): i2cRead returned Error -1
[ 10847][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[ 10850][E][Wire.cpp:513] requestFrom(): i2cRead returned Error -1

when I used the I2c scan program, I got 0x20 and 0x51 with [Wire.begin(PIN_IIC_SDA, PIN_IIC_SCL, (uint32_t)800000);]
![cst820](https://github.com/Xinyuan-LilyGO/T-RGB/assets/5342949/f68bad63-9521-48c8-b5d5-9c7fc238d216)
![box_top](https://github.com/Xinyuan-LilyGO/T-RGB/assets/5342949/bd617c45-9292-4257-aa79-9c7320447e45)
![box_bottom](https://github.com/Xinyuan-LilyGO/T-RGB/assets/5342949/b9a37936-7f19-481f-aefd-5f046b780f5b)
![20231120_213502](https://github.com/Xinyuan-LilyGO/T-RGB/assets/5342949/71e0cf85-6329-4e0f-9785-72c9f154b587)

**Comment by lewisxhe** [comment]
The chip of CST only provides normal feedback when touched, and after timeout, it cannot receive any feedback on the i2c bus. It must be touched again to make CST work again
