### ISSUE TITLE
Serial.print does not work in "Factory" example

### ISSUE THREAD

**Issue by ThomasSlowhand** [Xinyuan-LilyGO/LilyGo-T-RGB#41]
Help/advice needed
I am using the T-RGB example "factory" (this app which is commonly installed on a T-RGB at supply), as a framework for creating a new app, but the "Serial.print" debug function does not work, even if "Serial.begin(115200)" is declared in the beginning of "void setup()". normally. This is not an installation fault, as the Serial.print function works with other apps on the same device. Any help is highly appreciated.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-RGB/assets/22990954/1f379d6e-69b3-431a-84ad-914667eb0ae7)
CDC must turn on

**Comment by ThomasSlowhand** [comment]
Hello Lewis,

many thanks, problem solved!

BR,
Thomas
