### ISSUE TITLE
Analog in

### ISSUE THREAD

**Issue by ThomasSlowhand** [Xinyuan-LilyGO/LilyGo-T-RGB#46]
Is it possible to re-assign a pin on the T-RGB for enabling an Analog-in corresponding to PA12 on a Bluepill? 

(https://stm32-base.org/boards/STM32F103C8T6-Blue-Pill.html).

Background: I am thinking about connecting a atomic clock receiver

https://universal-solder.ca/product/60khz-wwvb-atomic-clock-receiver/

to the device for getting synchronized time w/o NTP.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/assets/22990954/7ce9af51-1231-4fee-ab93-72f4247a1d86)
If you must choose one, then IO0 may be the best choice. If it is used as an analog input, you need to remove the pull-up resistor. It depends on how you choose.

**Comment by ThomasSlowhand** [comment]
Many thanks, Lewis, your swift reply and help is highly appreciated.

**Comment by lewisxhe** [comment]
If it's ok, I close it

**Comment by ThomasSlowhand** [comment]
Hello Lewis,

can you assist? I’d need a power consumption table for T-SIM 7600-H in all operation modes to check and plan a öong-term application with reduced power availability.

Mit freundlichen Grüßen,
best regards

Thomas Krim
Watch the Ernst Westphal TV Report!<https://ernst-westphal.de/video/Ernst-Westphal-web.mp4>


Ernst Westphal e. K.
Passion for watches. Since 1898.


German traditional wholesale supply for sophisticated watchmaking and chronometry
Deutscher Traditions-Fachgroßhandel für Feinuhrmacherei und Chronometrie

Hamburg/Germany
Handelsregister HRA 47518 – AG Hamburg
USt. ID-Nr.  DE175597301
