### ISSUE TITLE
LilyGo_RGBPanel.h compile error

### ISSUE THREAD

**Issue by savall21** [Xinyuan-LilyGO/LilyGo-T-RGB#47]
When I try to compile any of the examples using LilyGo_RGBPanel.h, I get compile errors stemming from line #24 #include <ExtensionIOXL9555.hpp>.  Where is "ExtensionIOXL9555.hpp"??

**Comment by lewisxhe** [comment]
Do you use platformio or arduino?
Using Arduino IDE or platformio will automatically download dependencies, ExtensionIOXL9555 is located
[ExtensionIOXL9555.hpp](https://github.com/lewisxhe/SensorLib/blob/master/src/ExtensionIOXL9555.hpp)

I ran a compile check and found no problems
https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/actions/runs/8261965632

https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/actions/runs/8261963905

**Comment by savall21** [comment]
I'm using Arduino IDE. My errors:
In file included from /Users/chriscarpenter/Downloads/lilygo/LilyGo-T-RGB-main/examples/lv_factory/lv_factory.ino:10:
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:103:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO cs = ExtensionIOXL9555::IO3;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:104:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO mosi = ExtensionIOXL9555::IO4;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:105:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO sclk = ExtensionIOXL9555::IO5;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:106:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO reset = ExtensionIOXL9555::IO6;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:107:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO power_enable = ExtensionIOXL9555::IO2;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:108:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO sdmmc_cs = ExtensionIOXL9555::IO7;
                        ^~~~~~~~~~~~~
/Users/chriscarpenter/Documents/Arduino/libraries/LilyGo-T-RGB/src/LilyGo_RGBPanel.h:109:24: error: 'ExtensionGPIO' in 'class ExtensionIOXL9555' does not name a type
     ExtensionIOXL9555::ExtensionGPIO tp_reset = ExtensionIOXL9555::IO1;
                        ^~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

**Comment by lewisxhe** [comment]
Which version of esp32 core are you using? 3.0?

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/assets/22990954/fa74d0e5-79a6-439f-b99b-f2a321bbfad4)
Can you compare to see if the installation is complete?

**Comment by savall21** [comment]
Thats the thing.  When I'm in ArduinoIDO and I search the Library for LilyGo-T-RGB, I don't get anything.  I imported the zip file from github

**Comment by lewisxhe** [comment]
To import files, you must manually download dependent libraries instead of simply importing LilyGo-T-RGB.

https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB#5%EF%B8%8F%E2%83%A3-arduino-ide-manual-installation

**Comment by lewisxhe** [comment]
You can't find it? ?

![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/assets/22990954/196040e6-031b-43bd-b0bc-457bcffc070a)

**Comment by savall21** [comment]
SensorLib in the library only gives me an option up to version 0.1.4

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/assets/22990954/c1439ed3-b8a3-43e2-b0d1-4a204d2759bb)


> SensorLib in the library only gives me an option up to version 0.1.4

**Comment by savall21** [comment]
![Screenshot 2024-03-13 at 5 23 47 AM](https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/assets/68520841/e8d90b60-9e80-47c0-bcc4-06d795dcb724) No, I don't see it

**Comment by lewisxhe** [comment]
oh ! I don’t know what the situation is there, you can run the command line according to action CI
https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/blob/f9249cc55c71f011fab2e5a20354702727f67546/.github/workflows/arduino_ci.yml#L53

**Comment by lewisxhe** [comment]
I suspect that your ArduinoIDE failed to pull the library index library, resulting in the inability to index the latest library.

**Comment by savall21** [comment]
Wow, ok let me try that

**Comment by savall21** [comment]
Installed the latest version of Arduino IDE and reverted to lvgl 8.3.1 and it now compiles. Thanks!
