### ISSUE TITLE
Wake on Touch - getting the display to work again

### ISSUE THREAD

**Issue by DrJaymz** [Xinyuan-LilyGO/LilyGo-T-RGB#48]
I need a bit of help here - I wanted to sleep and then wake from a touch event.  I wake up the screen comes back on but is all sorts of messed up.  When waking from deep sleep I was under the impression that the board effectively resets and so the screen should be initialised as on power on.
_Originally posted by @DrJaymz in https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/issues/23#issuecomment-1999866497_

I cobbled the below from various places.  I don't see a sleep example in the current repo.

```
void deep_sleep(void)
{
    vTaskDelete(batteryMonitorTask);
    Serial.println("DEEP SLEEP !!!!");
    pinMode(TP_INT_PIN, INPUT);
    while (!digitalRead(TP_INT_PIN))
    {
        Serial.println("Wait touch release!");
        // It is necessary to read the touch message, otherwise the interrupt level will remain at 0
           static int16_t x, y;
        panel.getPoint(&x,&y);// touch.read();
        delay(200);
    }
    delay(2000);
    Serial.println("Touch release!!!");
    digitalWrite(pwmChannel,0);
    Serial.println("Enter deep sleep");
    delay(1000);

    // esp_sleep_enable_ext1_wakeup(1ULL << BOOT_BTN_PIN, ESP_EXT1_WAKEUP_ALL_LOW);

    esp_sleep_enable_ext1_wakeup(1ULL << TP_INT_PIN, ESP_EXT1_WAKEUP_ALL_LOW);
    esp_deep_sleep_start();
}
```

**Comment by lewisxhe** [comment]
Which model of touch chip do you use?

**Comment by DrJaymz** [comment]
> Which model of touch chip do you use?

Its the 2.8 inch model so thats a gt911 or something (dont have it in front of me)

**Comment by lewisxhe** [comment]
Examples have been added to test GT911 and CST820 versions
