### ISSUE TITLE
No touch

### ISSUE THREAD

**Issue by Suneboe** [Xinyuan-LilyGO/LilyGo-T-RGB#49]
I've dowloaded the repository and opened in PlatformIO. I can build and upload all examples but the touch interface does not work for any of them. I have the 2.1" half circle with FT3267. It did work for the example already on the device from factory. What should I be looking for?

**Comment by lewisxhe** [comment]
Oh. I just tested the CST820 and GT911 versions yesterday, but I didn’t test the FT3267. I don’t have this screen now. Please give me a day to investigate. The screen should be in my hands tomorrow.

**Comment by lewisxhe** [comment]
The fix has been submitted, please try it

**Comment by Suneboe** [comment]
Tested and it works 👍 Thank you
FYI - there's a typo in the platformio.ini. In the list of examples the "AdjustBacklight" is spelled "AdjustBlacklight" which makes it fail to find it when building

**Comment by lewisxhe** [comment]
Thanks for reminding

**Comment by Suneboe** [comment]
Thanks for the fast response. Commenting to close issue
