### ISSUE TITLE
2.1" Half Circle Touch Sleep(?)

### ISSUE THREAD

**Issue by IAmOrion** [Xinyuan-LilyGO/LilyGo-T-RGB#50]
I just purchased the 2.1" LilyGo-T-RGB half circle.  

I've made a simple UI and was playing around with it.  It's quite literally a screen with some text on it I guess similar to the Hello World example.  I've noticed the touch (or screen? but I'm assuming touch) seems to go to sleep within about 30 seconds on not being used.  The problem with this is that it then seems to take a few attempts at touching the screen to wake it up and register a touch event.

How can I prevent this sleep or whatever is happening?

**Comment by lewisxhe** [comment]
Read the coordinates again when the touch is interrupted
