### ISSUE TITLE
How draw color by TFT?

### ISSUE THREAD

**Issue by wang2956** [Xinyuan-LilyGO/LilyGo-T-RGB#53]
Does have tft.pushPixels input way?

**Comment by lewisxhe** [comment]
Do you want to use TFT_eSPI? Then you can use the TFT_eSPI_Sprite example, but you have to remember that you can't call any tft.xxxx functions, only Sprite
https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/tree/main/examples/TFT_eSPI_Sprite
