### ISSUE TITLE
Using XL9535 expander

### ISSUE THREAD

**Issue by s54b32julian** [Xinyuan-LilyGO/LilyGo-T-RGB#56]
I want to using the Port1 of the XL9535 Port expander (for general purpose digital Input or Outputs), that is used in databus class Arduino_XL9535SWSPI. But i´m not sure how to access it from outside.
All the correct functions are already there like PinMode, digitalRead/Write etc. but how can i call them in the main program to access them?

**Comment by lewisxhe** [comment]
Why do we need to access them? XL95535 is not connected to the outside world, and even if we access them, we can only control the display. And the purpose of writing this library is not to require users to control
