### ISSUE TITLE
[request] The board, plastic spacer and battery 3d models

### ISSUE THREAD

**Issue by hpsaturn** [Xinyuan-LilyGO/LilyGo-T-RGB#6]
## Overview

I'm working in a 3d printer box model to protect the board. Is possible that I'll have the 3d models referenced in this images?

![screenshot20221113_175344](https://user-images.githubusercontent.com/423856/201533811-2abfa669-f2a7-41d4-8e45-529635feeaa4.jpg)
![screenshot20221113_175258](https://user-images.githubusercontent.com/423856/201533814-bb22d1ec-c5d2-4f2a-93b8-b9b42cb25135.jpg)
 
I have a initial version, but this models could help me a lot:

https://user-images.githubusercontent.com/423856/201533918-d268d12f-5b67-4009-ac89-074e4cd3fddd.mp4

![photo_2022-11-13_17-50-47](https://user-images.githubusercontent.com/423856/201533956-991fae61-506c-4193-bd70-893541c0a3b6.jpg)

Thanks in advanced

**Comment by mmMicky** [comment]
The models provided by the repository can be used arbitrarily.
https://github.com/Xinyuan-LilyGO/T-RGB/tree/main/Shell_file

**Comment by hpsaturn** [comment]
thanks @mmMicky I didn't know, I'm going to try to convert it to Linux.

**Comment by PlastiBots** [comment]
Can you provide STL versions of the model pls?

**Comment by PlastiBots** [comment]
Hi @mmMicky, can you provide STL versions please?

**Comment by mmMicky** [comment]
I am not a structural designer. I don't know how to convert it,

**Comment by PlastiBots** [comment]
The CAD package should be able to export it as STL.

**Comment by hpsaturn** [comment]
I released a version of my box, maybe if anyone try to test it, any feedback is welcome:
![photo_2023-01-08_17-03-29](https://user-images.githubusercontent.com/423856/211209017-c03f3a9e-53a4-40f4-8335-246c60d928e2.jpg)

https://twitter.com/hpsaturn/status/1612129582194343937

**Comment by sandmen** [comment]
Looks awesome...
Thingiverse project contains one file/model with all parts, as one part.
I can not imaging, that I can put the T-RGB device into this model.

**Comment by hpsaturn** [comment]
please, read the description or "summary" in the Thingiverse post..

**Comment by euphi** [comment]
> The models provided by the repository can be used arbitrarily. https://github.com/Xinyuan-LilyGO/T-RGB/tree/main/Shell_file

It seems that the step file is the T-Watch model, not the T-RGB.

Can you provide the correct STEP file?

**Comment by sicca95** [comment]
Hi, everyone. Could you upload the correct STEP file from which has been taken the view of the display.dxf file? Thanks

**Comment by euphi** [comment]
Bump
