### ISSUE TITLE
esp_lcd_rgb_panel_config_t

### ISSUE THREAD

**Issue by staticengineer** [Xinyuan-LilyGO/LilyGo-T-RGB#60]
Ever since the new update ive had this error I cant seem to fix 

c:\Users\OEM\Documents\Arduino\libraries\LilyGo-T-RGB\src\LilyGo_RGBPanel.cpp: In member function 'void LilyGo_RGBPanel::initBUS()':
c:\Users\OEM\Documents\Arduino\libraries\LilyGo-T-RGB\src\LilyGo_RGBPanel.cpp:444:5: error: 'esp_lcd_rgb_panel_config_t' has no non-static data member named 'on_frame_trans_done'
  444 |     };
      |     ^

exit status 1

Compilation error: exit status 1

**Comment by lewisxhe** [comment]
Lower the esp version, it must be lower than 3.0
![image](https://github.com/user-attachments/assets/b40eee9d-026a-40b5-8807-6e5ec0034df9)
