### ISSUE TITLE
Touch screen with ft3267 controller not working

### ISSUE THREAD

**Issue by aleskramzar** [Xinyuan-LilyGO/LilyGo-T-RGB#63]
I am using the T-RGB display with the T-RGB 2.1 inch Half Circle display that has the ft3267 controller on it.

I am using the 1.0.3 version of the repo code with the  Touchpad.ino example.
I also have another reference display T-RGB 2.1 inch Full Circle with the CST820 controller and it works fine on the same code and board.

The RGB-interface works on both displays. they both show the correct image so both displays are ok. It is just the touch component that doesnt work on the half circle model.

After digging in the code for a while, i found out the getModelName() function returns 0 , while the on the working touch controller it returns 1 (LILYGO_T_RGB_2_1_INCHES macro).

Could i get some info on how to make the ft3267 version work?

**Comment by lewisxhe** [comment]
Have you tried this patch? https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB/commit/447f19f536134121a7b3335ad02e8feb25538bea
