### ISSUE TITLE
Ambient conditions

### ISSUE THREAD

**Issue by Bastler1980** [Xinyuan-LilyGO/LilyGo-T-RGB#64]
I would like to use the RGB-T display outdoors. I am aware that I will have to create an enclosure for the circuit board. Is there any information on storage and operating conditions for the display? I am thinking of temperature and humidity. 
Thank you very much for your support.

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/7e407c7e-56a6-4f32-b139-69ceca8dfbb5)
