### ISSUE TITLE
Bad PSRAM?

### ISSUE THREAD

**Issue by Grippy98** [Xinyuan-LilyGO/LilyGo-T-RGB#66]
I have a 2.8" T-RGB that was running the stock image, however flashing any image via platformIO or the lv_factory.bin image results in fails on the serial console:

![default_fw_flash](https://github.com/user-attachments/assets/cb0fa347-a477-4f44-8574-5be9b53c84d7)

`12:28:06.313 > ELF file SHA256: 5d96aefd860f3b46
12:28:06.313 >
12:28:06.403 > Rebooting...
12:28:06.415 > ESP-ROM:esp32s3-20210327
12:28:06.415 > Build:Mar 27 2021
12:28:06.415 > rst:0xc (RTC_SW_CPU_RST),boot:0x39 (SPI_FAST_FLASH_BOOT)
12:28:06.440 > Saved PC:0x420557d2
12:28:06.440 >   #0  0x420557d2 in esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_pm/pm_impl.c:855   
12:28:06.440 >
12:28:06.440 > SPIWP:0xee
12:28:06.447 > mode:DIO, clock div:1
12:28:06.447 > load:0x3fce3808,len:0x4bc
12:28:06.447 > load:0x403c9700,len:0xbd8
12:28:06.447 > load:0x403cc700,len:0x2a0c
12:28:06.447 > entry 0x403c98d0
12:28:06.534 > E (124) opi psram: PSRAM ID read error: 0x00000000, PSRAM chip not found or not supported, or wrong PSRAM line mode
12:28:06.539 > E (124) spiram: SPI RAM enabled but initialization failed. Bailing out.
12:28:06.584 > 
12:28:06.639 > assert failed: bool LilyGo_RGBPanel::begin(LilyGo_RGBPanel_Color_Order) LilyGo_RGBPanel.cpp:56 (false)
12:28:06.644 >
12:28:06.644 >
12:28:06.644 > Backtrace: 0x40377ae6:0x3fcebaa0 0x4037dbdd:0x3fcebac0 0x40383c5d:0x3fcebae0 0x4202bf97:0x3fcebc10 0x42001e99:0x3fcebc30 0x4202d666:0x3fcebc50
12:28:06.779 >   #0  0x40377ae6 in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408       
12:28:06.779 >   #1  0x4037dbdd in esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137
12:28:06.779 >   #2  0x40383c5d in __assert_func at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/assert.c:85
12:28:06.779 >   #3  0x4202bf97 in LilyGo_RGBPanel::begin(LilyGo_RGBPanel_Color_Order) at src/LilyGo_RGBPanel.cpp:56
12:28:06.779 >   #4  0x42001e99 in setup() at C:/Users/andre/Documents/LilyGo-T-RGB/examples/DeepSleep/DeepSleep.ino:42
12:28:06.779 >   #5  0x4202d666 in loopTask(void*) at C:/Users/andre/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:42`

**Comment by lewisxhe** [comment]
1. For Arduino versions below 3.0, we recommend using 2.0.14
2. Tools -> PSRAM -> OPI PSRAM, see README
3. You did not check the firmware in Flash Tools
![image](https://github.com/user-attachments/assets/be0adac5-ffbd-41a8-9c70-b5b2e705119b)
