### ISSUE TITLE
3D CAD for the 2.8in T-RGB

### ISSUE THREAD

**Issue by martinroger** [Xinyuan-LilyGO/LilyGo-T-RGB#71]
Similar to #65 ... is there a CAD model of the 2.8in version ? It would help to integrate it in custom enclosures.

**Comment by lewisxhe** [comment]
Not yet, I have reported the requirement to LilyGo, it should be added soon

**Comment by lewisxhe** [comment]
Already added

**Comment by martinroger** [comment]
Closed by 9e87d42e3938030ebf7235b4877ac482ca0da4b4
